./PHONY: all task1 task2 task3 killer

all: task1 task2 task3 killer

task1: task1.c
	gcc -Wall -Wextra $^ -o $@

task2: task2.c
	gcc -Wall -Wextra $^ -o $@

task3: task3.c
	gcc -Wall -Wextra $^ -o $@

killer: killer.c
	gcc -Wall -Wextra $^ -o $@